name: Code Quailty and Linter

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.x

      - name: Install Python dependencies
        run: pip install black flake8

      - name: Run linters
        uses: wearerequired/lint-action@v1
        if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.owner.login == github.repository_owner }}
        with:
          black: true
          flake8: true
          black_args: "--line-length=79"
          flake8_args: "--max-line-length=79 --ignore=E203,E266,E501,W503 --select=B,C,E,F,W,T4,B9"
          auto_fix: true
